CREATE TABLE CUSTOMER_REWARD (
ID BIGINT PRIMARY KEY ,
CUSTOMER_ID BIGINT NOT NULL,
CUSTOMER_NAME VARCHAR(200) NOT NULL,
TRANS_COST     DOUBLE NOT NULL,
TRANSACTION_DATE        VARCHAR(20) NOT NULL
);